#! /bin/sh

if [ ! -e /userdata/edge_gw_config/identity.json ] ; then
  # This should not be needed, but hey maestro keeps crashing on me
  # TODO: remove this if when maestro reliably gets an ip
  if [ -z "$(ip addr show eth0 | grep 'inet ')" ] ; then
    udhcpc -n
  fi
  exit 7
fi
