unixLogSocket: /tmp/grease.socket
sysLogSocket: /dev/log
linuxKernelLog: true
httpUnixSocket: /tmp/maestroapi.sock
configDBPath: /userdata/etc/maestroConfig.db
clientId: "{{ARCH_SERIAL_NUMBER}}"
network:
    disable: true
platform_readers:
  - platform: "fsonly"
    params:
      identityPath: "/userdata/edge_gw_config/identity.json"
gateway_capabilities:
  edge_core_socketpath: "/tmp/edge.sock"
  lwm2m_objectid: 33457
  gateway_resources:
  - name: "urn:fid:pelion.com:log:1.0.0"
    enable: true
    config_filepath: "/etc/td-agent-bit/td-agent-bit.conf"
  - name: "urn:fid:pelion.com:terminal:1.0.0"
    enable: true
    config_filepath: "{{EDGE_ETC}}/pe-terminal/config.json"
  - name: "urn:fid:pelion.com:kaas:1.0.0"
    enable: true
    config_filepath: "/wigwag/system/var/lib/kubelet/kubeconfig"
var_defs:
   - key: "TMP_DIR"
     value: "/tmp"
   - key: "FOG_PROXY_ADDR"
     value: "gateways.local:8080"
   - key: "MAESTRO_RUNNER_DIR"
     value: "/wigwag/devicejs-core-modules/maestroRunner"
   - key: "EDGE_ETC"
     value: "/wigwag/system/etc"
mdns:
  static_records:
   - name: "WigWagRelay"
     service: "_wwservices._tcp"  # normally something like https or ftp
     interfaces: "eth0"
     not_interfaces: "Witap0"
     port: 3131
     text:
      - "wwid={{ARCH_SERIAL_NUMBER}}"
     hostname: "wigwaggateway"
   - name: "WigWagRelay_{{ARCH_SERIAL_NUMBER}}"
     service: "_wwservices._tcp"  # normally something like https or ftp
     interfaces: "eth0"
     not_interfaces: "Witap0"
     port: 3131
     text:
      - "wwid={{ARCH_SERIAL_NUMBER}}"
     hostname: "{{ARCH_SERIAL_NUMBER}}"
symphony: # symphony system management APIs
    disable_sys_stats: true
    sys_stats_count_threshold: 15     # send if you have 15 or more stats queued
    sys_stats_time_threshold: 120000  # every 120 seconds send stuff, no matter what
    no_tls: true
    host: "gateways.local"
    url_logs: "http://{{FOG_PROXY_ADDR}}/relay-logs/logs"
    url_stats: "http://{{FOG_PROXY_ADDR}}/relay-stats/stats_obj"
    send_time_threshold: 120000       # set the send time threshold to 2 minutes
targets:
   - file: "/wigwag/log/maestro_gw.log"
     rotate:
         max_files: 4
         max_file_size: 10000000  # 10MB max file size
         max_total_size: 42000000
         rotate_on_start: true
     delim: "\n"
     format_time: "[%ld:%d] "
     format_level: "<%s> "
     format_tag: "{%s} "
     format_origin: "(%s) "
     filters:
       - levels: warn
         format_pre: "\u001B[33m"    # yellow
         format_post: "\u001B[39m"
       - levels: error
         format_pre: "\u001B[31m"    # red
         format_post: "\u001B[39m"
static_file_generators:
   - name: "relayTerm"
     template_file: "/wigwag/etc/template/relayTerm.template.json"
     output_file: "{{EDGE_ETC}}/pe-terminal/config.json"
config_end: true
